In [1]:
x = 17

In [2]:
print(x)

17


In [3]:
x+=1
print(x)

18


## Pandas

In [7]:
import pandas as pd

df = pd.read_csv("data/liverpool.csv")
print(df)

        Unnamed: 0 position  born  number nationality
0  Roberto Firmino       FW  1991   no. 9      Brazil
1       Sadio Mane       FW  1992  no. 10     Senegal
2    Mohamed Salah       FW  1992  no. 11       Egypt
3        Joe Gomez       DF  1997  no. 12     England
4   Alisson Becker       GK  1992  no. 13      Brazil


In [6]:
df

Unnamed: 0 position  born  number nationality
0  Roberto Firmino       FW  1991   no. 9      Brazil
1       Sadio Mane       FW  1992  no. 10     Senegal
2    Mohamed Salah       FW  1992  no. 11       Egypt
3        Joe Gomez       DF  1997  no. 12     England
4   Alisson Becker       GK  1992  no. 13      Brazil

## numpy

In [8]:
import numpy as np
array1 = np.array([2,3,4,5,6])
print(array1)

[2 3 4 5 6]


In [9]:
type(array1)

numpy.ndarray

In [11]:
array1.shape

(5,)

In [17]:
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array2)
type(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


numpy.ndarray

In [19]:
array2.shape

(3, 4)

In [22]:
print(array1.size, array2.size)

5 12


In [45]:
array3 = np.full(10, 3)
array4 = [3 for _ in range(10)]
array5 = np.zeros(10, dtype=int)
array6 = np.ones(10, dtype=int)
array7 = np.random.random(10)
array8 = np.arange(10)
array9 = np.arange(1, 10)
array10 = np.arange(1, 10,3)
print(array3, "\t"*2,"  : " ,type(array3))
print(array4, "\t"*2,"  : " ,type(array4))
print(array5, "\t"*2,"  : " ,type(array5))
print(array6, "\t"*2,"  : " ,type(array6))
print(array7, "\t"*2,"  : " ,type(array7))
print(array8, "\t"*2,"  : " ,type(array8))
print(array9, "\t"*2,"  : " ,type(array9))
print(array10, "\t"*2,"  : " ,type(array10))


[3 3 3 3 3 3 3 3 3 3] 		   :  <class 'numpy.ndarray'>
[3, 3, 3, 3, 3, 3, 3, 3, 3, 3] 		   :  <class 'list'>
[0 0 0 0 0 0 0 0 0 0] 		   :  <class 'numpy.ndarray'>
[1 1 1 1 1 1 1 1 1 1] 		   :  <class 'numpy.ndarray'>
[5.06637011e-01 9.39294945e-01 4.03996460e-01 7.03562438e-01
 1.04125128e-04 9.93696803e-01 3.18776999e-01 3.12584830e-01
 1.38592702e-01 8.67983324e-01] 		   :  <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9] 		   :  <class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9] 		   :  <class 'numpy.ndarray'>
[1 4 7] 		   :  <class 'numpy.ndarray'>
